# Generated by Django 5.0.2 on 2025-12-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('tablet', 'Планшет'), ('laptop', 'Ноутбук'), ('desktop', 'ПК')], max_length=20, verbose_name='Тип устройства')),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi'), ('other', 'Другое')], max_length=20, verbose_name='Производитель')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='PhonePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('screen', 'Экран'), ('battery', 'Батарея'), ('camera', 'Камера'), ('keyboard', 'Клавиатура'), ('other', 'Другое')], max_length=20, verbose_name='Тип комплектующей')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.device', verbose_name='Устройство')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PKPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(choices=[('processor', 'Процессор'), ('ram', 'Оперативная память'), ('storage', 'Накопитель'), ('power_supply', 'Блок питания'), ('motherboard', 'Материнская плата'), ('case', 'Корпус'), ('graphics_card', 'Видеокарта'), ('other', 'Другое')], max_length=20, verbose_name='Тип комплектующей')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.device', verbose_name='Устройство')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
