# Generated by Django 5.0.2 on 2025-12-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('tablet', 'Планшет'), ('laptop', 'Ноутбук'), ('desktop', 'ПК'), ('other', 'Другое')], max_length=20, verbose_name='Тип устройства')),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi'), ('honor', 'Honor'), ('asus', 'Asus'), ('lenovo', 'Lenovo'), ('msi', 'MSI'), ('acer', 'Acer'), ('dell', 'Dell'), ('lg', 'LG'), ('hp', 'HP'), ('other', 'Другое')], max_length=20, verbose_name='Производитель')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('screen', 'Экран'), ('battery', 'Батарея'), ('camera', 'Камера'), ('keyboard', 'Клавиатура'), ('processor', 'Процессор'), ('ram', 'Оперативная память'), ('storage', 'Накопитель'), ('power_supply', 'Блок питания'), ('motherboard', 'Материнская плата'), ('case', 'Корпус'), ('graphics_card', 'Видеокарта'), ('other', 'Другое')], max_length=20, verbose_name='Тип комплектующей')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.device', verbose_name='Устройство')),
            ],
        ),
    ]
