# Generated by Django 5.0.2 on 2025-12-12 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.device', verbose_name='Устройство')),
                ('master', models.ForeignKey(blank=True, limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_orders', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('parts', models.ManyToManyField(blank=True, to='warehouse.part', verbose_name='Запчасти')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('parts_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость деталей')),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость работ')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки по смете')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='orders.order', verbose_name='Заявка')),
            ],
        ),
    ]
